### PR TITLE
Fix parquet tests

### PR DESCRIPTION
**Pull request by sambles**
### Fixed parquet output checks and update expected results 

* Fixed platform test runner, needs this branch to run https://github.com/OasisLMF/OasisPlatform/pull/666
* Updated expected results for `6_case` and `8_case` https://github.com/OasisLMF/OasisPlatform/issues/645
* Added `RUN_MDK` option to ci for skipping the cli run checks

#### Case 8 (example) 
```
{
  "gul_S1_qelt.parquet": "PASSED",
  "gul_S1_melt.parquet": "PASSED",
  "gul_S1_mplt.parquet": "PASSED",
  "ri_S1_qelt.parquet": "FAILED", --floating point
  "gul_S1_summary-info.csv": "PASSED",
  "il_S1_melt.parquet": "FAILED", --floating point
  "gul_S1_ept.parquet": "PASSED",
  "ri_S1_mplt.parquet": "FAILED", --less rows compared with case 7 csv
  "gul_S1_psept.parquet": "PASSED",
  "ri_S1_selt.parquet": "FAILED",
  "ri_S1_melt.parquet": "FAILED",
  "il_S1_qelt.parquet": "FAILED",
  "il_S1_selt.parquet": "FAILED",
  "gul_S1_qplt.parquet": "PASSED",
  "gul_S1_palt.parquet": "PASSED",
  "il_S1_psept.parquet": "FAILED",
  "gul_S1_selt.parquet": "PASSED",
  "ri_S1_summary-info.csv": "PASSED",
  "il_S1_palt.parquet": "FAILED",
  "ri_S1_palt.parquet": "PASSED",
  "ri_S1_splt.parquet": "FAILED",
  "il_S1_summary-info.csv": "PASSED",
  "ri_S1_qplt.parquet": "FAILED",
  "il_S1_splt.parquet": "FAILED",
  "ri_S1_psept.parquet": "FAILED",
  "il_S1_qplt.parquet": "FAILED",
  "il_S1_ept.parquet": "FAILED",
  "il_S1_mplt.parquet": "FAILED",
  "ri_S1_ept.parquet": "FAILED",
  "gul_S1_splt.parquet": "PASSED"
}
```

### CODE REVIEW

**Comment by sambles** [comment]
Results need checking, I looked a a few files and it looked to be small floating point differences 
https://ci.oasislmfdev.org/blue/organizations/jenkins/oasis_PiWind/detail/PR-97/2/pipeline

**Comment by johcarter** [comment]
some are just floating point, but I have found one where the parquet file has less rows than the csv 

@hchagani-oasislmf please could you take a look at 8_case/output/ri_S1_mplt.parquet  versus 7_case/output/ri_S1_mplt.csv which should contain the same results data? nb the expected results on develop branch are wrong too, but slightly different num rows

**Comment by hchagani-oasislmf** [comment]
Opened a ktools issue for the missing results data: https://github.com/OasisLMF/ktools/issues/308.

**Comment by sambles** [comment]
Note: Still some differences in **chanceofloss*, leaving this open for @johcarter  

[check_script.sh.txt](https://github.com/OasisLMF/OasisPiWind/files/9072949/check_script.sh.txt)
[case_7_vs_8_diffs.txt](https://github.com/OasisLMF/OasisPiWind/files/9072945/case_7_vs_8_diffs.txt)

**Comment by hchagani-oasislmf** [comment]
> Note: Still some differences in **chanceofloss**, leaving this open for @johcarter
> 
> [check_script.sh.txt](https://github.com/OasisLMF/OasisPiWind/files/9072949/check_script.sh.txt) [case_7_vs_8_diffs.txt](https://github.com/OasisLMF/OasisPiWind/files/9072945/case_7_vs_8_diffs.txt)

I think this is OK as the chance of loss metric has been redefined (see https://github.com/OasisLMF/ktools/pull/307 for more details).

**Comment by sambles** [comment]
Thanks @hchagani-oasislmf  the csv tests needed updating to match chance of loss update

**Comment by sambles** [comment]
https://ci.oasislmfdev.org/blue/organizations/jenkins/oasis_PiWind/detail/PR-97/17/pipeline/

**Pull request merged**
