### PR TITLE
Add port and release tag variables

### PR DESCRIPTION
**Pull request by cdlhub**
Add variables for keys service port and model release tag to be used in conjunction with Deployment repo.

### CODE REVIEW

**Comment by sr-murthy** [comment]
As this is related to deployment it is best to have @sambles review it.

**Comment by sr-murthy** [comment]
@cdlhub We've removed the `develop` branch in PiWind - `master` is the default again. Could you please resubmit your PR from your branch to target `master`?

**Comment by cdlhub** [comment]
@sr-murthy Done. See PR https://github.com/OasisLMF/OasisPiWind/pull/23

**Comment by cdlhub** [comment]
@sr-murthy It also comes with PR https://github.com/OasisLMF/Deployment/pull/11

**Pull request closed without merging**
